# Generated by Django 4.2 on 2024-01-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_post',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
