# Generated by Django 4.2 on 2024-01-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_platform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
