# Generated by Django 4.2 on 2024-01-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_platform', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.IntegerField(max_length=200)),
                ('image', models.CharField(default='NA', max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
