# Generated by Django 4.2 on 2024-01-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_platform', '0002_alter_add_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_post',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
