# Generated by Django 4.2 on 2024-01-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_platform', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_post',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
