# Generated by Django 4.2 on 2024-01-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_platform', '0003_alter_add_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_post',
            name='title',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
