# Generated by Django 4.2 on 2024-01-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_platform', '0004_alter_add_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_post',
            name='content',
            field=models.CharField(default='NA', max_length=1500),
        ),
        migrations.AddField(
            model_name='add_post',
            name='summary',
            field=models.CharField(default='NA', max_length=50000),
        ),
    ]
