# Generated by Django 4.2 on 2024-01-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_platform', '0004_alter_add_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_post',
            name='content',
            field=models.CharField(default='NA', max_length=2500),
        ),
    ]
