# Generated by Django 4.2 on 2024-01-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_platform', '0005_add_post_content_add_post_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_post',
            name='author',
        ),
    ]
