# Generated by Django 4.2 on 2024-01-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_platform', '0005_alter_add_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_post',
            name='content',
            field=models.CharField(default='Default content', max_length=2500),
        ),
        migrations.AlterField(
            model_name='add_post',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
